language: bash
services: docker

env:
  - VERSION=9.0 VARIANT=jdk8-slim
  - VERSION=9.0 VARIANT=jdk8
  - VERSION=9.0 VARIANT=jdk11-slim
  - VERSION=9.0 VARIANT=jdk11
  - VERSION=8.5 VARIANT=jdk8-slim
  - VERSION=8.5 VARIANT=jdk8
  - VERSION=8.5 VARIANT=jdk11-slim
  - VERSION=8.5 VARIANT=jdk11
  - VERSION=7 VARIANT=jdk8-slim
  - VERSION=7 VARIANT=jdk8

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash
  - cd "$VERSION/$VARIANT"
  - image="tomcat:$VERSION-$VARIANT"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      docker build -t "$image" .
      ~/official-images/test/run.sh "$image"
    )

after_script:
  - docker images

# vim:set et ts=2 sw=2:
